[project]
name = "python-3-sqlmodel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.0"
dependencies = [
    "faker==30.8.2",
    "pillow==11.0.0",
    "sqlmodel==0.0.22",
]
